#ifndef USER_CONFIG_CAN_ID_H
#define USER_CONFIG_CAN_ID_H

// 发命令：DJI GM6020 电机组 1 (电机1-4)
#define CAN_STDID_DJI_GROUP1 0x200U
// 发命令：DJI GM6020 电机组 2 (电机5-8)
#define CAN_STDID_DJI_GROUP2 0x2FFU

// GM6020 反馈 ID 基址：ID1=0x205，ID2=0x206 ...
#define GM6020_FEEDBACK_BASE_STDID 0x205U

// 云台物理 CAN ID
#define GIMBAL_YAW_CAN_ID   2U
#define GIMBAL_PITCH_CAN_ID 4U

// 收反馈：云台 Yaw 电机
#define CAN_STDID_GIMBAL_YAW_FB   (GM6020_FEEDBACK_BASE_STDID + (GIMBAL_YAW_CAN_ID - 1U))
// 收反馈：云台 Pitch 电机
#define CAN_STDID_GIMBAL_PITCH_FB (GM6020_FEEDBACK_BASE_STDID + (GIMBAL_PITCH_CAN_ID - 1U))

#endif // USER_CONFIG_CAN_ID_H
